x-generator: NSwag v14.4.0.0 (NJsonSchema v11.3.2.0 (Newtonsoft.Json v13.0.0.0))
openapi: 3.0.0
info:
  title: My Title
  version: 1.0.0
paths:
  /api/WeatherReadings:
    get:
      tags:
      - WeatherReadings
      operationId: WeatherReadings_GetAll
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/WeatherReading'
    post:
      tags:
      - WeatherReadings
      operationId: WeatherReadings_Add
      requestBody:
        x-name: reading
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WeatherReading'
        required: true
        x-position: 1
      responses:
        201:
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WeatherReading'
        400:
          description: ''
          content:
            application/json:
              schema:
                type: string
  /api/WeatherReadings/latest:
    get:
      tags:
      - WeatherReadings
      operationId: WeatherReadings_GetLatest
      parameters:
      - name: location
        in: query
        schema:
          type: string
        x-position: 1
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WeatherReading'
components:
  schemas:
    WeatherReading:
      type: object
      additionalProperties: false
      properties:
        id:
          type: integer
          format: int32
        location:
          type: string
        temperatureC:
          type: number
          format: double
        humidityPercent:
          type: number
          format: double
        timestamp:
          type: string
          format: date-time
